version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-android:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - node/install:
          node-version: '20.14.0'
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Install Expo CLI
          command: npm install -g expo-cli
      - run:
          name: Prebuild Android native folder
          command: npx expo prebuild --platform android --clean
      - run:
          name: Build APK with Gradle
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: aiacon-release.apk

workflows:
  build:
    jobs:
      - build-android:
          filters:
            branches:
              only: main
