version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-android:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - node/install:
          node-version: '20.14.0'
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Install ninja-build
          command: sudo apt-get update && sudo apt-get install -y ninja-build
      - run:
          name: Install EAS CLI
          command: npm install --legacy-peer-deps -g eas-cli
      - run:
          name: EAS Login
          command: eas whoami
      - run:
          name: Build Android APK
          command: eas build --platform android --local --non-interactive --output ./build/aiacon.apk
      - store_artifacts:
          path: ./build/aiacon.apk
          destination: aiacon-debug.apk

workflows:
  build:
    jobs:
      - build-android:
          filters:
            branches:
              only: main
